apiVersion: v1
kind: Service
metadata:
  name: ml-service-nodeport
spec:
  selector:
    app: ml-service
  type: NodePort
  ports:
    - port: 80 # Service port
      targetPort: 9699 # Container port
      nodePort: 30000 # Host port mapped by Kind (used in our first setup step)